# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set PATH variable
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
        echo "name=REPOSITORY_NAME" >> $GITHUB_ENV 
        $(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate mod sprites
      run: ./gradlew tools:gen
    - name: Build jar file
      run: ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: Substructure
        path: core/build/libs/Substructure.jar
