name: Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Android SDK
      uses: android-actions/setup-android@v2.0.1
    - name: Set PATH variable
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate mod sprites
      run: ./gradlew tools:gen
    - name: Build jar file
      run: ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: Substructure
        path: core/build/libs/Substructure.jar
